import {
  AbsoluteFill,
  useCurrentFrame,
  interpolate,
  spring,
  useVideoConfig,
} from 'remotion';

export const EndSlide = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  
  const titleOpacity = spring({
    frame,
    fps,
    config: { damping: 100, stiffness: 200, mass: 0.5 },
  });
  
  const subtitleOpacity = spring({
    frame: frame - 30,
    fps,
    config: { damping: 100, stiffness: 200, mass: 0.5 },
  });

  const ctaOpacity = spring({
    frame: frame - 60,
    fps,
    config: { damping: 100, stiffness: 200, mass: 0.5 },
  });

  const sparkleScale = interpolate(
    frame,
    [0, 30, 60, 90],
    [1, 1.2, 1, 1.1],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }
  );

  return (
    <AbsoluteFill
      style={{
        background: 'linear-gradient(135deg, #1f2937 0%, #374151 100%)',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 80,
      }}
    >
      <div
        style={{
          textAlign: 'center',
        }}
      >
        <div
          style={{
            opacity: titleOpacity,
            fontSize: 64,
            marginBottom: 30,
            transform: `scale(${sparkleScale})`,
          }}
        >
          ✨
        </div>
        
        <h1
          style={{
            opacity: titleOpacity,
            fontSize: 52,
            fontWeight: 'bold',
            color: 'white',
            margin: 0,
            marginBottom: 30,
            textShadow: '0 4px 20px rgba(0,0,0,0.3)',
            fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
          }}
        >
          Strategy Complete!
        </h1>
        
        <div
          style={{
            opacity: subtitleOpacity,
            fontSize: 28,
            color: 'rgba(255,255,255,0.9)',
            marginBottom: 40,
            lineHeight: 1.3,
            fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
          }}
        >
          Your AI-powered marketing strategy is ready for implementation
        </div>
        
        <div
          style={{
            opacity: ctaOpacity,
            background: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
            padding: '20px 40px',
            borderRadius: 50,
            display: 'inline-block',
            boxShadow: '0 10px 30px rgba(59, 130, 246, 0.3)',
          }}
        >
          <div
            style={{
              fontSize: 24,
              color: 'white',
              fontWeight: 'bold',
              fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
            }}
          >
            🚀 Ready to Launch
          </div>
        </div>
        
        <div
          style={{
            opacity: ctaOpacity,
            fontSize: 18,
            color: 'rgba(255,255,255,0.7)',
            marginTop: 30,
            fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
          }}
        >
          Generated by AI Agent Company
        </div>
      </div>
    </AbsoluteFill>
  );
};